// Pure reference data — no framework, DB, or network imports.
//
// Country→currency default + ISO 4217 validation (ADR-0032, CONTEXT.md Dealer
// Country). A Market Quote's Dealer Country supplies the default local currency;
// the researcher may override to any other single active ISO 4217 code. The
// override picker is driven by ISO_4217_CURRENCIES; isValidCurrency is the
// forward-only write-path gate (pre-existing free-text values are tolerated
// elsewhere, never re-validated here).

import { ISO_3166_COUNTRY_NAMES, type CountryName } from "../benchmark-items/countries";

export interface Currency {
  readonly code: string;
  readonly name: string;
}

/** The active ISO 4217 codes (code + display name) the override picker lists. */
export const ISO_4217_CURRENCIES: readonly Currency[] = [
  { code: "AED", name: "UAE Dirham" },
  { code: "AFN", name: "Afghani" },
  { code: "ALL", name: "Lek" },
  { code: "AMD", name: "Armenian Dram" },
  { code: "ANG", name: "Netherlands Antillean Guilder" },
  { code: "AOA", name: "Kwanza" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "AWG", name: "Aruban Florin" },
  { code: "AZN", name: "Azerbaijan Manat" },
  { code: "BAM", name: "Convertible Mark" },
  { code: "BBD", name: "Barbados Dollar" },
  { code: "BDT", name: "Taka" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "BIF", name: "Burundi Franc" },
  { code: "BMD", name: "Bermudian Dollar" },
  { code: "BND", name: "Brunei Dollar" },
  { code: "BOB", name: "Boliviano" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "BSD", name: "Bahamian Dollar" },
  { code: "BTN", name: "Ngultrum" },
  { code: "BWP", name: "Pula" },
  { code: "BYN", name: "Belarusian Ruble" },
  { code: "BZD", name: "Belize Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "CDF", name: "Congolese Franc" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "CNY", name: "Yuan Renminbi" },
  { code: "COP", name: "Colombian Peso" },
  { code: "CRC", name: "Costa Rican Colon" },
  { code: "CUP", name: "Cuban Peso" },
  { code: "CVE", name: "Cabo Verde Escudo" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "DJF", name: "Djibouti Franc" },
  { code: "DKK", name: "Danish Krone" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "ERN", name: "Nakfa" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "EUR", name: "Euro" },
  { code: "FJD", name: "Fiji Dollar" },
  { code: "GBP", name: "Pound Sterling" },
  { code: "GEL", name: "Lari" },
  { code: "GHS", name: "Ghana Cedi" },
  { code: "GMD", name: "Dalasi" },
  { code: "GNF", name: "Guinean Franc" },
  { code: "GTQ", name: "Quetzal" },
  { code: "GYD", name: "Guyana Dollar" },
  { code: "HNL", name: "Lempira" },
  { code: "HTG", name: "Gourde" },
  { code: "HUF", name: "Forint" },
  { code: "IDR", name: "Rupiah" },
  { code: "ILS", name: "New Israeli Sheqel" },
  { code: "INR", name: "Indian Rupee" },
  { code: "IQD", name: "Iraqi Dinar" },
  { code: "IRR", name: "Iranian Rial" },
  { code: "ISK", name: "Iceland Krona" },
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "JPY", name: "Yen" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "KGS", name: "Som" },
  { code: "KHR", name: "Riel" },
  { code: "KMF", name: "Comorian Franc" },
  { code: "KPW", name: "North Korean Won" },
  { code: "KRW", name: "Won" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "KZT", name: "Tenge" },
  { code: "LAK", name: "Lao Kip" },
  { code: "LBP", name: "Lebanese Pound" },
  { code: "LKR", name: "Sri Lanka Rupee" },
  { code: "LRD", name: "Liberian Dollar" },
  { code: "LSL", name: "Loti" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "MDL", name: "Moldovan Leu" },
  { code: "MGA", name: "Malagasy Ariary" },
  { code: "MKD", name: "Denar" },
  { code: "MMK", name: "Kyat" },
  { code: "MNT", name: "Tugrik" },
  { code: "MRU", name: "Ouguiya" },
  { code: "MUR", name: "Mauritius Rupee" },
  { code: "MVR", name: "Rufiyaa" },
  { code: "MWK", name: "Malawi Kwacha" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "MZN", name: "Mozambique Metical" },
  { code: "NAD", name: "Namibia Dollar" },
  { code: "NGN", name: "Naira" },
  { code: "NIO", name: "Cordoba Oro" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "OMR", name: "Rial Omani" },
  { code: "PAB", name: "Balboa" },
  { code: "PEN", name: "Sol" },
  { code: "PGK", name: "Kina" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "PKR", name: "Pakistan Rupee" },
  { code: "PLN", name: "Zloty" },
  { code: "PYG", name: "Guarani" },
  { code: "QAR", name: "Qatari Rial" },
  { code: "RON", name: "Romanian Leu" },
  { code: "RSD", name: "Serbian Dinar" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "RWF", name: "Rwanda Franc" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "SBD", name: "Solomon Islands Dollar" },
  { code: "SCR", name: "Seychelles Rupee" },
  { code: "SDG", name: "Sudanese Pound" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "SLE", name: "Leone" },
  { code: "SOS", name: "Somali Shilling" },
  { code: "SRD", name: "Surinam Dollar" },
  { code: "SSP", name: "South Sudanese Pound" },
  { code: "STN", name: "Dobra" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "SZL", name: "Lilangeni" },
  { code: "THB", name: "Baht" },
  { code: "TJS", name: "Somoni" },
  { code: "TMT", name: "Turkmenistan New Manat" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "TOP", name: "Pa'anga" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "TTD", name: "Trinidad and Tobago Dollar" },
  { code: "TWD", name: "New Taiwan Dollar" },
  { code: "TZS", name: "Tanzanian Shilling" },
  { code: "UAH", name: "Hryvnia" },
  { code: "UGX", name: "Uganda Shilling" },
  { code: "USD", name: "US Dollar" },
  { code: "UYU", name: "Peso Uruguayo" },
  { code: "UZS", name: "Uzbekistan Sum" },
  { code: "VED", name: "Bolivar Soberano" },
  { code: "VND", name: "Dong" },
  { code: "VUV", name: "Vatu" },
  { code: "WST", name: "Tala" },
  { code: "XAF", name: "CFA Franc BEAC" },
  { code: "XCD", name: "East Caribbean Dollar" },
  { code: "XOF", name: "CFA Franc BCEAO" },
  { code: "YER", name: "Yemeni Rial" },
  { code: "ZAR", name: "Rand" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "ZWG", name: "Zimbabwe Gold" },
];

// Valid-code lookup keyed by canonical (uppercase) code, derived from the
// bundled list so the picker and the validator can never drift apart.
const VALID_CODES: ReadonlySet<string> = new Set(
  ISO_4217_CURRENCIES.map((c) => c.code),
);

/** Collapse surrounding whitespace and case for tolerant code matching. */
function normaliseCurrencyKey(value: string): string {
  return value.trim().toUpperCase();
}

/**
 * Whether `code` is a known active ISO 4217 code. Tolerant of case and
 * surrounding whitespace; blank and unknown input are rejected.
 */
export function isValidCurrency(code: string): boolean {
  return VALID_CODES.has(normaliseCurrencyKey(code));
}

/**
 * The default local currency for a Dealer Country. Total over CountryName —
 * every canonical country name has an entry, so this never returns undefined.
 */
export function defaultCurrencyForCountry(country: CountryName): string {
  return COUNTRY_DEFAULT_CURRENCY[country];
}

const COUNTRY_DEFAULT_CURRENCY: Record<CountryName, string> = {
  Afghanistan: "AFN",
  Albania: "ALL",
  Algeria: "DZD",
  Andorra: "EUR",
  Angola: "AOA",
  "Antigua and Barbuda": "XCD",
  Argentina: "ARS",
  Armenia: "AMD",
  Australia: "AUD",
  Austria: "EUR",
  Azerbaijan: "AZN",
  Bahamas: "BSD",
  Bahrain: "BHD",
  Bangladesh: "BDT",
  Barbados: "BBD",
  Belarus: "BYN",
  Belgium: "EUR",
  Belize: "BZD",
  Benin: "XOF",
  Bhutan: "BTN",
  Bolivia: "BOB",
  "Bosnia and Herzegovina": "BAM",
  Botswana: "BWP",
  Brazil: "BRL",
  Brunei: "BND",
  Bulgaria: "BGN",
  "Burkina Faso": "XOF",
  Burundi: "BIF",
  "Cabo Verde": "CVE",
  Cambodia: "KHR",
  Cameroon: "XAF",
  Canada: "CAD",
  "Central African Republic": "XAF",
  Chad: "XAF",
  Chile: "CLP",
  China: "CNY",
  Colombia: "COP",
  Comoros: "KMF",
  Congo: "XAF",
  "Costa Rica": "CRC",
  Croatia: "EUR",
  Cuba: "CUP",
  Cyprus: "EUR",
  Czechia: "CZK",
  "Democratic Republic of the Congo": "CDF",
  Denmark: "DKK",
  Djibouti: "DJF",
  Dominica: "XCD",
  "Dominican Republic": "DOP",
  Ecuador: "USD",
  Egypt: "EGP",
  "El Salvador": "USD",
  "Equatorial Guinea": "XAF",
  Eritrea: "ERN",
  Estonia: "EUR",
  Eswatini: "SZL",
  Ethiopia: "ETB",
  Fiji: "FJD",
  Finland: "EUR",
  France: "EUR",
  Gabon: "XAF",
  Gambia: "GMD",
  Georgia: "GEL",
  Germany: "EUR",
  Ghana: "GHS",
  Greece: "EUR",
  Grenada: "XCD",
  Guatemala: "GTQ",
  Guinea: "GNF",
  "Guinea-Bissau": "XOF",
  Guyana: "GYD",
  Haiti: "HTG",
  Honduras: "HNL",
  Hungary: "HUF",
  Iceland: "ISK",
  India: "INR",
  Indonesia: "IDR",
  Iran: "IRR",
  Iraq: "IQD",
  Ireland: "EUR",
  Israel: "ILS",
  Italy: "EUR",
  "Ivory Coast": "XOF",
  Jamaica: "JMD",
  Japan: "JPY",
  Jordan: "JOD",
  Kazakhstan: "KZT",
  Kenya: "KES",
  Kiribati: "AUD",
  Kosovo: "EUR",
  Kuwait: "KWD",
  Kyrgyzstan: "KGS",
  Laos: "LAK",
  Latvia: "EUR",
  Lebanon: "LBP",
  Lesotho: "LSL",
  Liberia: "LRD",
  Libya: "LYD",
  Liechtenstein: "CHF",
  Lithuania: "EUR",
  Luxembourg: "EUR",
  Madagascar: "MGA",
  Malawi: "MWK",
  Malaysia: "MYR",
  Maldives: "MVR",
  Mali: "XOF",
  Malta: "EUR",
  "Marshall Islands": "USD",
  Mauritania: "MRU",
  Mauritius: "MUR",
  Mexico: "MXN",
  Micronesia: "USD",
  Moldova: "MDL",
  Monaco: "EUR",
  Mongolia: "MNT",
  Montenegro: "EUR",
  Morocco: "MAD",
  Mozambique: "MZN",
  Myanmar: "MMK",
  Namibia: "NAD",
  Nauru: "AUD",
  Nepal: "NPR",
  Netherlands: "EUR",
  "New Zealand": "NZD",
  Nicaragua: "NIO",
  Niger: "XOF",
  Nigeria: "NGN",
  "North Korea": "KPW",
  "North Macedonia": "MKD",
  Norway: "NOK",
  Oman: "OMR",
  Pakistan: "PKR",
  Palau: "USD",
  Palestine: "ILS",
  Panama: "PAB",
  "Papua New Guinea": "PGK",
  Paraguay: "PYG",
  Peru: "PEN",
  Philippines: "PHP",
  Poland: "PLN",
  Portugal: "EUR",
  Qatar: "QAR",
  Romania: "RON",
  Russia: "RUB",
  Rwanda: "RWF",
  "Saint Kitts and Nevis": "XCD",
  "Saint Lucia": "XCD",
  "Saint Vincent and the Grenadines": "XCD",
  Samoa: "WST",
  "San Marino": "EUR",
  "Sao Tome and Principe": "STN",
  "Saudi Arabia": "SAR",
  Senegal: "XOF",
  Serbia: "RSD",
  Seychelles: "SCR",
  "Sierra Leone": "SLE",
  Singapore: "SGD",
  Slovakia: "EUR",
  Slovenia: "EUR",
  "Solomon Islands": "SBD",
  Somalia: "SOS",
  "South Africa": "ZAR",
  "South Korea": "KRW",
  "South Sudan": "SSP",
  Spain: "EUR",
  "Sri Lanka": "LKR",
  Sudan: "SDG",
  Suriname: "SRD",
  Sweden: "SEK",
  Switzerland: "CHF",
  Syria: "SYP",
  Taiwan: "TWD",
  Tajikistan: "TJS",
  Tanzania: "TZS",
  Thailand: "THB",
  "Timor-Leste": "USD",
  Togo: "XOF",
  Tonga: "TOP",
  "Trinidad and Tobago": "TTD",
  Tunisia: "TND",
  Turkey: "TRY",
  Turkmenistan: "TMT",
  Tuvalu: "AUD",
  Uganda: "UGX",
  Ukraine: "UAH",
  "United Arab Emirates": "AED",
  "United Kingdom": "GBP",
  "United States": "USD",
  Uruguay: "UYU",
  Uzbekistan: "UZS",
  Vanuatu: "VUV",
  "Vatican City": "EUR",
  Venezuela: "VED",
  Vietnam: "VND",
  Yemen: "YER",
  Zambia: "ZMW",
  Zimbabwe: "USD",
};

// Defensive: assert no country is missing a currency at module load. This is
// the runtime mirror of the Record<CountryName, string> compile-time guard and
// the "no gaps" acceptance test.
for (const name of ISO_3166_COUNTRY_NAMES) {
  if (!COUNTRY_DEFAULT_CURRENCY[name]) {
    throw new Error(`No default currency mapped for country: ${name}`);
  }
}
